"""Integration 7A autograder.

CI runs `make smoke` first, then this autograder. Tests validate:
- The pipeline regenerated predictions_smoke.csv from the substitute model.
- The submitted predictions.csv has the right shape and row count.
- apply.py reads MODEL_HUB_ID from the env (no hard-coded model name).
- apply.py reads label names from model.config.id2label (no hard-coded class lists).
- README updated (length + huggingface.co URL).
- domain-shift-analysis.md template has been filled in (length).
"""
import ast
import os
import re
import subprocess

import pandas as pd
import pytest

REPO_ROOT = os.path.join(os.path.dirname(__file__), "..")


def test_make_smoke_exits_zero():
    """Verify make smoke ran and produced output (CI invokes `make smoke` before pytest)."""
    smoke_csv = os.path.join(REPO_ROOT, "predictions_smoke.csv")
    assert os.path.isfile(smoke_csv), \
        "predictions_smoke.csv must be generated by `make smoke` (run before pytest in CI)"


def test_smoke_predictions_generated_by_pipeline():
    """Smoke predictions must have the right schema and probabilities in [0, 1]."""
    smoke_csv = os.path.join(REPO_ROOT, "predictions_smoke.csv")
    df = pd.read_csv(smoke_csv)
    for col in ["article_id", "text_excerpt", "predicted_label", "predicted_probability"]:
        assert col in df.columns, f"missing column in smoke output: {col}"
    assert df["predicted_probability"].between(0.0, 1.0).all()
    assert len(df) >= 5


def test_submitted_predictions_csv_columns():
    csv_path = os.path.join(REPO_ROOT, "predictions.csv")
    assert os.path.isfile(csv_path), "predictions.csv must be committed (real run against your fine-tuned model)"
    df = pd.read_csv(csv_path)
    for col in ["article_id", "text_excerpt", "predicted_label", "predicted_probability"]:
        assert col in df.columns


def test_submitted_predictions_csv_row_count():
    df = pd.read_csv(os.path.join(REPO_ROOT, "predictions.csv"))
    assert len(df) == 1033, f"predictions.csv must have 1033 rows (full tech-news corpus); found {len(df)}"


def test_submitted_predictions_probabilities_in_range():
    df = pd.read_csv(os.path.join(REPO_ROOT, "predictions.csv"))
    assert df["predicted_probability"].between(0.0, 1.0).all(), \
        "predicted_probability must be in [0, 1]; you may be writing logits instead of probabilities"


def test_apply_uses_hub_id():
    """apply.py must read MODEL_HUB_ID from the environment, not hard-code a model name.

    Heuristic: only catches a literal-string `from_pretrained("some-org/...")`.
    A learner who assigns the model id to a local variable first
    (`model_id = "user/model"; from_pretrained(model_id)`) slips past this
    check. We accept that gap — the MODEL_HUB_ID requirement above plus the
    SI demo + TA review covers the case in practice. Tightening the check
    would require AST analysis, which is overkill for the failure mode.
    """
    src = open(os.path.join(REPO_ROOT, "apply.py")).read()
    assert "MODEL_HUB_ID" in src, \
        "apply.py must read MODEL_HUB_ID from the environment"
    # Heuristic: no hard-coded `from_pretrained("some-org/...")` literal in the source
    hard_coded = re.findall(r'from_pretrained\(\s*"[^"]+"\s*\)', src)
    for match in hard_coded:
        # Allow loading by a variable; flag any literal model id
        if "/" in match:
            pytest.fail(
                f"apply.py appears to hard-code a model id: {match}. "
                "Read MODEL_HUB_ID from the environment instead."
            )


def test_labels_read_from_model_config():
    """apply.py must derive label names from model.config.id2label, not hard-code them."""
    src = open(os.path.join(REPO_ROOT, "apply.py")).read()

    # Required: a reference to id2label
    assert "id2label" in src, \
        "apply.py must read label names from model.config.id2label"

    # Forbidden: a hard-coded list of class names
    tree = ast.parse(src)
    for node in ast.walk(tree):
        if isinstance(node, ast.List):
            elts = [e for e in node.elts if isinstance(e, ast.Constant) and isinstance(e.value, str)]
            if len(elts) >= 2:
                literals = {e.value.lower() for e in elts}
                if {"positive", "negative"}.issubset(literals) or {"positive", "neutral", "negative"}.issubset(literals):
                    pytest.fail(
                        f"apply.py contains a hard-coded list of label names: {literals}. "
                        "Read labels from model.config.id2label instead — the CI substitute is binary, your real model is 3-class."
                    )


def test_makefile_targets_present():
    mk = open(os.path.join(REPO_ROOT, "Makefile")).read()
    for target in ("apply", "smoke", "clean"):
        assert re.search(rf"^{target}\s*:", mk, re.MULTILINE), \
            f"Makefile must define a `{target}` target"


def test_readme_updated():
    """README must have been substantively updated AND contain an HF Hub URL.

    Threshold (2200 chars) is set above the unmodified starter (1553 chars) so
    that learners must add the model URL + reproduction command + the two
    explanatory paragraphs to clear the bar.
    """
    readme = open(os.path.join(REPO_ROOT, "README.md")).read()
    assert len(readme) > 2200, \
        f"README.md is too short ({len(readme)} chars). Add the model URL, reproduction notes, " \
        "and the explanatory paragraphs requested in the starter README's TODO section."
    assert "huggingface.co/" in readme, \
        "README.md must include the learner's Hugging Face Hub model URL"


def test_analysis_md_exists_and_nonempty():
    """The starter ships a 1,272-char template with section headings + _TODO_
    placeholders. Threshold (1500 chars) requires the learner to fill in
    real content beyond the scaffold — replacing _TODO_ with prose that
    answers each section's prompt.
    """
    path = os.path.join(REPO_ROOT, "domain-shift-analysis.md")
    assert os.path.isfile(path)
    contents = open(path).read()
    assert len(contents) >= 1500, \
        f"domain-shift-analysis.md is too short ({len(contents)} chars). " \
        "Replace each _TODO_ placeholder with substantive content for that section."
